name: ci

on:
  pull_request:
    branches: [main]

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.0"
      
      - name: Go unit tests
        run: go test -cover ./...

      - name: Install gosec for Go 1.21.1+
        run: go install github.com/securego/gosec/v2/cmd/gosec@latest

      - name: Gosec check for security issues
        run: gosec ./...

  style:
    name: Style
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4
      
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.0"

      - name: Go formating check
        run: test -z $(go fmt ./...)

      - name: Install staticcheck for Go 1.17+
        run: go install honnef.co/go/tools/cmd/staticcheck@latest
      
      - name: Static check for linting issues
        run: staticcheck ./...